### ISSUE TITLE
ERROR:  KeyError: 'id'  when I try to import Dashboard on existing ORG Grafana

### ISSUE THREAD

**Issue by dalvarezquiroga** [k8spin/grafana-multi-tenant-operator#27]
Hello,

Thanks for the powerfull tool. 
I am trying to import a JSON dashboard in a exiting Organization previously created and it json doesn't contain "id" value. Only contain UID by default I am using Grafana 7.3.5, here you can find an example:

```  {
        ....
        "timezone": "",
        "title": "Example",
        "uid": "tfriddrRY",  --> Only UID
        "version": 1
      }
```

And if I see response from pod doing "kubectl logs -f pod/grafana-multi-tenant-operator I found an error"

```
File "/src/grafana/dashboard.py", line 20, in create
    del jsonDashboard['id']
KeyError: 'id'
```

I think probably we need to add some check about ID row in JSON. I can fix it, if you agree with that.

**Comment by angelbarrera92** [comment]
Ciao @dalvarezquiroga!

Seems like we require to have the `id` in the dashboard json definition. 🤔 Honestly, I don't think it is required as far as we are removing it from the definition to actually create it.

So maybe we can implement a `safe` delete of the `id` attribute. Can you take ownership of the issue?

Thanks!
